---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-viewer
  namespace: pipeline-musr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-viewer
  template:
    metadata:
      labels:
        app: trace-viewer
    spec:
      restartPolicy: Always
      containers:
        - name: trace-viewer
          image: ghcr.io/stfc-icd-research-and-design/supermusr-trace-viewer:58f442f32709b9483d407a2a023a0e470ef577c3
          args:
            - --broker=130.246.53.247:9092
            - --consumer-group=trace-viewer-0
            - --trace-topic=traces-in
            - --digitiser-event-topic=daq-events
            - --broker-name="MuSR (main spectrometer)"
            # - --server-path=trace-viewer/
          env:
            - name: RUST_LOG
              value: "debug"
          resources:
            limits:
              memory: 500Mi
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: trace-viewer
  namespace: pipeline-musr
spec:
  selector:
    app: trace-viewer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: trace-viewer-http
  namespace: pipeline-musr
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      # match: Host(`ndw2982.isis.cclrc.ac.uk`) && PathPrefix(`/trace-viewer`)
      match: Host(`ndw2982.isis.cclrc.ac.uk`)
      middlewares:
        - name: strip-trace-viewer-prefix
      services:
        - name: trace-viewer
          port: 3000

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-trace-viewer-prefix
  namespace: pipeline-musr
spec:
  stripPrefix:
    prefixes:
      - /trace-viewer
