services:
  event-formation:
    profiles:
      - main
      - main-and-test-event-formation
      - main-and-test-digitiser-aggregator
      - main-and-test-nexus-writer
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 500m
    restart: on-failure
    logging:
      options:
        path: /home/dankirk/pipeline-test/archive/incoming/${PIPELINE_NAME}/logs/event-formation.log
    image: localhost/supermusr-trace-to-events
    environment:
      - RUST_LOG=${RUST_LOG}
      - NO_COLOR=${NO_COLOR}
      - OTEL_LOG=${OTEL_LOG}
    command:
      - --broker=${BROKER}
      - --consumer-group=${GROUP_EVENT_FORMATION}
      - --trace-topic=${TRACE_TOPIC}
      - --event-topic=${DAT_EVENT_TOPIC}
      - --observability-address=${OBSV_ADDRESS_EVENT_FORMATION}
      - ${OTEL_ENDPOINT}
      - --otel-namespace=${PIPELINE_NAME}
      - --polarity=${EF_POLARITY}
      - --baseline=${EF_BASELINE}
      - ${EF_INPUT_MODE}
      - --threshold=${EF_FTD_THRESHOLD}
      - --duration=${EF_FTD_DURATION}
      - --cool-off=${EF_FTD_COOLOFF}
    volumes:
      - ../${NEXUS_ARCHIVE_HOST_PATH}/logs:/logs

  frame-aggregation:
    profiles:
      - main
      - main-and-test-event-formation
      - main-and-test-digitiser-aggregator
      - main-and-test-nexus-writer
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 500m
    restart: on-failure
    logging:
      options:
        path: /home/dankirk/pipeline-test/archive/incoming/${PIPELINE_NAME}/logs/digitiser-aggregator.log
    image: localhost/supermusr-digitiser-aggregator
    environment:
      - RUST_LOG=${RUST_LOG}
      - NO_COLOR=${NO_COLOR}
      - OTEL_LOG=${OTEL_LOG}
    command:
      - --broker=${BROKER}
      - --group=${GROUP_AGGREGATOR}
      - --observability-address=${OBSV_ADDRESS_AGGREGATOR}
      - --input-topic=${DAT_EVENT_TOPIC}
      - --output-topic=${FRAME_EVENT_TOPIC}
      - ${OTEL_ENDPOINT}
      - ${OTEL_LEVEL_AGGREGATOR}
      - --otel-namespace=${PIPELINE_NAME}
      - --frame-ttl-ms=${FRAME_TTL_MS}
      - ${DIGITISERS}
    volumes:
      - ../${NEXUS_ARCHIVE_HOST_PATH}/logs:/logs

  nexus-writer:
    profiles:
      - main
      - main-and-test-event-formation
      - main-and-test-digitiser-aggregator
      - main-and-test-nexus-writer
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 350m
    restart: on-failure
    logging:
      options:
        path: /home/dankirk/pipeline-test/archive/incoming/${PIPELINE_NAME}/logs/nexus-writer.log
    image: ghcr.io/stfc-icd-research-and-design/supermusr-nexus-writer:main
    environment:
      - RUST_LOG=${RUST_LOG}
      - NO_COLOR=${NO_COLOR}
      - OTEL_LOG=${OTEL_LOG}
    command:
      - --broker=${BROKER}
      - --consumer-group=${GROUP_WRITER}
      - --observability-address=${OBSV_ADDRESS_WRITER}
      - --frame-event-topic=${FRAME_EVENT_TOPIC}
      - --control-topic=${CONTROL_TOPIC}
      - --log-topic=${LOGS_TOPIC}
      - --sample-env-topic=${SELOGS_TOPIC}
      - --alarm-topic=${ALARMS_TOPIC}
      - --cache-run-ttl-ms=${RUN_TTL_MS}
      - --event-list-chunk-size=16384
      - ${OTEL_ENDPOINT}
      - ${OTEL_LEVEL_WRITER}
      - --otel-namespace=${PIPELINE_NAME}
      - --file-name=local
      - --archive-name=archive
    volumes:
      - ../${NEXUS_LOCAL_HOST_PATH}:/local
      - ../${NEXUS_ARCHIVE_HOST_PATH}:/archive
      - ../${NEXUS_ARCHIVE_HOST_PATH}/logs:/logs

  nexus-writer-test:
    profiles:
      - main-and-test-nexus-writer
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 350m
    restart: on-failure
    logging:
      options:
        path: /home/dankirk/pipeline-test/archive/incoming/hifi_test/logs/nexus-writer.log
    image: localhost/supermusr-nexus-writer
    environment:
      - RUST_LOG=${RUST_LOG}
      - NO_COLOR=${NO_COLOR}
      - OTEL_LOG=${OTEL_LOG}
    command:
      - --broker=${BROKER}
      - --consumer-group=nexus-writer-test
      - --observability-address=${OBSV_ADDRESS_WRITER}
      - --frame-event-topic=${FRAME_EVENT_TOPIC}
      - --control-topic=${CONTROL_TOPIC}
      - --log-topic=${LOGS_TOPIC}
      - --sample-env-topic=${SELOGS_TOPIC}
      - --alarm-topic=${ALARMS_TOPIC}
      - --cache-run-ttl-ms=${RUN_TTL_MS}
      - --event-list-chunk-size=16384
      - ${OTEL_ENDPOINT}
      - ${OTEL_LEVEL_WRITER}
      - --otel-namespace=hifi-test
      - --file-name=local
      - --archive-name=archive
    volumes:
      - ../Output/Local_test:/local
      - ../archive/incoming/hifi_test:/archive
      - ../archive/incoming/hifi_test/logs:/logs